on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Clone source code

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build!
      id: build_apk
      run: ./gradlew --no-daemon build

    # eventually i want to use this instead, because it generates fancy changelogs and i wont have to hard code values, 
    # but for now we'll use the easier option
    # - name: Release
    #   run: |
    #     npm install -g release@6
    #     release minor

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }} (FTC SDK 6.1)
        draft: false
        prerelease: false

    - name: Upload Release APK
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./TeamCode/build/outputs/apk/debug/TeamCode-release.apk
        asset_name: TeamCode-release.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload Debug APK
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./TeamCode/build/outputs/apk/debug/TeamCode-debug.apk
        asset_name: TeamCode-debug.apk
        asset_content_type: application/vnd.android.package-archive

