on:
  [pull_request, push]

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Format Code with Google Java Format
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
        name: Get Source Code
      - uses: actions/setup-java@v1
        name: Configure Java
        with:
          java-version: 11
      - uses: axel-op/googlejavaformat-action@v3
        name: Format
        with:
          # 4 spaces ftw
          args: "--aosp"
          commitMessage: "style: auto-format with Google Java Format"
          version: "1.9"
      
